<?php

// Plugin definition
$plugin = array(
  'title' => t('Springboard Bootstrap Homepage'),
  'category' => t('Springboard Bootstrap'),
  'icon' => 'homepage.png',
  'theme' => 'homepage',
  'regions' => array(
    'hero-intro' => t('Hero Area Intro'),
	'hero-fact1' => t('Hero Area Fact 1'),
	'hero-fact2' => t('Hero Area Fact 2'),
	'hero-fact3' => t('Hero Area Fact 3'),
      'hero-fact4' => t('Hero Area Fact 4'),
	'hero-video' => t('Hero Area Video'),
    'infographic' => t('Infographic Area'),
	'deckpreview' => t('Decks Preview'),
	'additional-resources-title' => t('Additional Resources Title'),
	'additional-resources-video2' => t('Additional Resources Video 2'),
	'additional-resources-video3' => t('Additional Resources Video 3'),
	'link-to-videos' => t('Link to Video Stories'),
	'additional-resources-poll' => t('Additional Resources Poll'),
  ),
);
